# Find OpenHITLS library and headers
#
# Sets:
#  OPENHITLS_FOUND
#  OPENHITLS_LIBRARIES
#  OPENHITLS_INCLUDE_DIRS

set(OPENHITLS_ROOT "" CACHE PATH "Prefix for OpenHITLS installation")
set(OPENHITLS_UNSUPPORTED_PLATFORM 0)

if (CMAKE_SYSTEM_NAME MATCHES "Emscripten|WASI|Generic")
	set(OPENHITLS_UNSUPPORTED_PLATFORM 1)
endif()

if (NOT OPENHITLS_UNSUPPORTED_PLATFORM)
	if ("${OPENHITLS_LIBRARIES}" STREQUAL "" OR "${OPENHITLS_INCLUDE_DIRS}" STREQUAL "")
		include(FindPkgConfig)
		PKG_SEARCH_MODULE(OPENHITLS openhitls)
	endif()

	set(_OPENHITLS_HINTS)
	if (OPENHITLS_ROOT)
		list(APPEND _OPENHITLS_HINTS ${OPENHITLS_ROOT})
	endif()
	list(APPEND _OPENHITLS_HINTS /usr/local /usr)

	if ("${OPENHITLS_INCLUDE_DIRS}" STREQUAL "")
		find_path(OPENHITLS_INCLUDE_DIRS hitls/tls/hitls.h
			PATHS ${_OPENHITLS_HINTS}
			PATH_SUFFIXES include)
	endif()

	if (OPENHITLS_INCLUDE_DIRS)
		set(_BASE "${OPENHITLS_INCLUDE_DIRS}")
		list(APPEND OPENHITLS_INCLUDE_DIRS "${_BASE}/hitls/bsl")
		list(APPEND OPENHITLS_INCLUDE_DIRS "${_BASE}/hitls/crypto")
		list(APPEND OPENHITLS_INCLUDE_DIRS "${_BASE}/hitls/pki")
		list(APPEND OPENHITLS_INCLUDE_DIRS "${_BASE}/hitls/tls")
	endif()

	if ("${OPENHITLS_LIBRARIES}" STREQUAL "")
		find_library(OPENHITLS_BSL_LIBRARY hitls_bsl
			PATHS ${_OPENHITLS_HINTS}
			PATH_SUFFIXES lib)
		find_library(OPENHITLS_CRYPTO_LIBRARY hitls_crypto
			PATHS ${_OPENHITLS_HINTS}
			PATH_SUFFIXES lib)
		find_library(OPENHITLS_TLS_LIBRARY hitls_tls
			PATHS ${_OPENHITLS_HINTS}
			PATH_SUFFIXES lib)
		find_library(OPENHITLS_PKI_LIBRARY hitls_pki
			PATHS ${_OPENHITLS_HINTS}
			PATH_SUFFIXES lib)
		if (OPENHITLS_BSL_LIBRARY AND OPENHITLS_CRYPTO_LIBRARY AND OPENHITLS_TLS_LIBRARY AND OPENHITLS_PKI_LIBRARY)
			set(OPENHITLS_LIBRARIES
				${OPENHITLS_BSL_LIBRARY}
				${OPENHITLS_CRYPTO_LIBRARY}
				${OPENHITLS_TLS_LIBRARY}
				${OPENHITLS_PKI_LIBRARY})
		endif()
	endif()
endif()

if (OPENHITLS_UNSUPPORTED_PLATFORM)
	set(OPENHITLS_FOUND 0)
elseif ("${OPENHITLS_LIBRARIES}" STREQUAL "" OR "${OPENHITLS_INCLUDE_DIRS}" STREQUAL "")
	set(OPENHITLS_FOUND 0)
else()
	set(OPENHITLS_FOUND 1)
endif()
